name: cnn_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.0
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - narwhals==2.11.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.33.1
      - pyarrow==21.0.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.51.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - watchdog==6.0.0
